### ISSUE TITLE
Build a dummy http server

### ISSUE THREAD

**Issue by moreirathomas** [benchttp/cobaye#1]
## Description

In development mode, having a local dummy http server to quickly test our product is a huge plus.
A simplistic one will do. 

## Tasks

- [ ] configure a http server
- [ ] write dummy handler functions
- [ ] support any http verb (`GET`, `POST`, ...)
- [ ] write dummy handler functions

## Suggestions

Write it in Go, reason is it has the lightest dependency footprint (code and environment, eg `gofmt`, `go test`) compared to node (typescript, eslint, jest and all the jazz). 

Be super simple. `main` function may just configure the server, route the handlers and launch the server.

Use Fibonacci suite as the handler internally called function. It is quick for small numbers and exponentially grows slower. It is an excellent behavior for our usecase, easily and predictably configurable :

```txt
GET dummy/fibonacci?n=3

POST dummy/fibonacci
{ "n" : 3 }
```
